import "./globals.css";
import { Inter } from "next/font/google";
import { NextIntlClientProvider, useLocale, useMessages } from "next-intl";
import { notFound } from "next/navigation";
import { ThemeProvider } from "./theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portafolio Duvan_Dev",
  description: "Generated by Duvan_Dev",
};

export default function RootLayout({ children, params }) {
  const locale = useLocale();

  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }

  const messages = useMessages();

  return (
    <html lang={locale}>
    <NextIntlClientProvider locale={locale} messages={messages}>
    <body className={`${inter.className} bg-whitebg dark:bg-black backdrop-blur-3xl`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <main>
                {children}
              </main>
        </ThemeProvider>
    </body>
    </NextIntlClientProvider>
  </html>
  );
}
